### ISSUE TITLE
Not compatible with iOS8

### ISSUE THREAD

**Issue by datomnurdin** [cwRichardKim/RKSwipeCards#10]
I test it your source code it runs smoothly on iOS7 but it showing weird in iOS8, the position of button and card not align properly. How I can tackle this problem?

**Comment by cwRichardKim** [comment]
hmm, do you mind sending me a screenshot? I just opened it with ios8 and it looks fine on my end

**Comment by omar-saadoun** [comment]
The problem is with Autolayout. I can´t adjust the size of the cards automatically.

**Comment by cwRichardKim** [comment]
Yea I personally hardly ever deal with AutoLayout. Did you manage to figure this out?

**Comment by raphi** [comment]
@omar-saadoun did you solve this issue?

**Comment by cwRichardKim** [comment]
oops i believe i resolved this issue a while ago
